// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaLWoeSFVWg6KAFuWO-kWC96x6HszwvOs',
    appId: '1:207872501897:web:ec09e6d43020bf59507e58',
    messagingSenderId: '207872501897',
    projectId: 'drp-31',
    authDomain: 'drp-31.firebaseapp.com',
    storageBucket: 'drp-31.appspot.com',
    measurementId: 'G-V3RS52Y61V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe2l5DdFhiX6L7IjC6qlH-v0vrdM0aTDM',
    appId: '1:207872501897:android:3c6cff9eea93bf85507e58',
    messagingSenderId: '207872501897',
    projectId: 'drp-31',
    storageBucket: 'drp-31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Fk8xtcQkjOivMqleSw7QjKLhhdwgsDQ',
    appId: '1:207872501897:ios:00f8e9ac88eff1bd507e58',
    messagingSenderId: '207872501897',
    projectId: 'drp-31',
    storageBucket: 'drp-31.appspot.com',
    iosBundleId: 'com.example.rishav.drp31',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Fk8xtcQkjOivMqleSw7QjKLhhdwgsDQ',
    appId: '1:207872501897:ios:00f8e9ac88eff1bd507e58',
    messagingSenderId: '207872501897',
    projectId: 'drp-31',
    storageBucket: 'drp-31.appspot.com',
    iosBundleId: 'com.example.rishav.drp31',
  );
}
