on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

name: Local Build

jobs:

  build:
  
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
          
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.0"
          cache: true
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Test
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug --split-per-abi

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}


